image: fbottarel/graspa-benchmark:latest
ports:
- port: 6080
  onOpen: notify
workspaceLocation: "."
tasks:
- init: export PATH="$PATH:/home/gitpod/.local"
- command: pip3 install -r GRASPA-benchmark/requirements.txt
- command: mkdir GRASPA-benchmark/build && cd GRASPA-benchmark/build && cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitpod/.local && make install
- command: git clone https://github.com/robotology-playground/GRASPA-test.git
- command: start-vnc-session.sh
- command: tmux
