image: ghcr.io/hsp-iit/graspa-benchmark:latest
ports:
- port: 8080
  onOpen: notify
workspaceLocation: "."
tasks:
- before: >
        mkdir -p GRASPA-benchmark/build &&
        cd GRASPA-benchmark/build &&
        cmake .. -DCMAKE_INSTALL_PREFIX=/home/gitpod/.local &&
        make install &&
        cd /workspace &&
        git clone https://github.com/hsp-iit/GRASPA-test.git
- init: /app/entrypoint.sh
- command: bash
