image: ghcr.io/hsp-iit/graspa-benchmark:latest
ports:
- port: 8080
  onOpen: notify
workspaceLocation: "."
tasks:
- init: cd GRASPA-benchmark/build && git pull master && cmake .. && make install
- command: cd GRASPA-test && git pull
- command: tmux
