image: pattacini/graspa-benchmark:latest
ports:
- port: 6080
  onOpen: notify
tasks:
- init: pip3 install numpy numpy-stl opencv-python opencv-contrib-python scipy
  command: start-vnc-session.sh
  command: tmux 
